name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        host: 'linux'
        target: 'android'
        arch: 'android_arm64_v8a'
        modules: 'qtmultimedia'
        tools: 'android'

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: build
      run: |
        cmake .. \
        -DCMAKE_BUILD_TYPE=Release \
        -DANDROID_ABI=arm64-v8a \
        -DANDROID_PLATFORM=android-23 \
        -DANDROID_NDK=$ANDROID_NDK_HOME \
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
        -DCMAKE_PREFIX_PATH=$Qt6_DIR \
        -DCMAKE_FIND_ROOT_PATH=$Qt6_DIR

    - name: Build
      working-directory: build
      run: cmake --build . --parallel

    - name: Create Android APK
      working-directory: build
      run: |
        make aab
        make apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/android-build/build/outputs/apk/release/*.apk 